### ISSUE TITLE
Error: spawn E2BIG

### ISSUE THREAD

**Issue by alliteration** [kishikawakatsumi/xcresulttool#547]
Getting the below error with my project. This is the configuration:

- name: Run unit tests
run: xcodebuild -project Ro.xcodeproj -scheme 'Pipeline' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' -resultBundlePath TestResults test
    - uses: kishikawakatsumi/xcresulttool@v1
      if: failure()
      with:
        path: TestResults.xcresult

And the error:

Error: spawn E2BIG
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at ToolRunner.<anonymous> (/Users/runner/work/_actions/kishikawakatsumi/xcresulttool/v1/webpack:/xcresulttool/node_modules/@actions/exec/lib/toolrunner.js:413:1)
    at Generator.next (<anonymous>)
    at /Users/runner/work/_actions/kishikawakatsumi/xcresulttool/v1/webpack:/xcresulttool/node_modules/@actions/exec/lib/toolrunner.js:27:1
    at new Promise (<anonymous>)
    at __webpack_modules__.8[15](https://github.com/HealthByRo/rocket/actions/runs/3624537612/jobs/6111622894#step:7:16)9.__awaiter (/Users/runner/work/_actions/kishikawakatsumi/xcresulttool/v1/webpack:/xcresulttool/node_modules/@actions/exec/lib/toolrunner.js:23:1)
    at /Users/runner/work/_actions/kishikawakatsumi/xcresulttool/v1/webpack:/xcresulttool/node_modules/@actions/exec/lib/toolrunner.js:395:1
    at new Promise (<anonymous>)
    at ToolRunner.<anonymous> (/Users/runner/work/_actions/kishikawakatsumi/xcresulttool/v1/webpack:/xcresulttool/node_modules/@actions/exec/lib/toolrunner.js:395:1)

**Comment by kishikawakatsumi** [comment]
@alliteration  Can you share your `TestResults.xcresult` to investigate the error?

**Comment by daltonclaybrook** [comment]
This issue is occurring for me as well. I DM'd you a copy of my `xcresult` file on Twitter. Two details that might be helpful in the search:
1. The `xcresult` file is the result of merging two other `xcresult` files: One was generated in a "build for testing" step, and the other in a "test without building" step.
2. I believe the `xcresult` contains attachments with failed snapshot test images from [this library](https://github.com/pointfreeco/swift-snapshot-testing/).

**Comment by daltonclaybrook** [comment]
Possibly some important context here: https://github.com/standard/standard/issues/40

**Comment by mackoj** [comment]
I did have the same issue is there any known way to go around it ?

**Comment by mackoj** [comment]
I think it's failling when the XCTestResult is too big.

**Comment by mackoj** [comment]
This is the exact issue 
```
Error: spawn E2BIG
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at Object.spawn (node:child_process:733:9)
    at ToolRunner.<anonymous> (/Users/runner/work/_actions/kishikawakatsumi/xcresulttool/v1/webpack:/xcresulttool/node_modules/@actions/exec/lib/toolrunner.js:413:1)
    at Generator.next (<anonymous>)
    at /Users/runner/work/_actions/kishikawakatsumi/xcresulttool/v1/webpack:/xcresulttool/node_modules/@actions/exec/lib/toolrunner.js:27:1
    at new Promise (<anonymous>)
    at __webpack_modules__.8[15](https://github.com/repo/project/actions/runs/6185365880/job/16790825777?pr=87#step:6:16)9.__awaiter (/Users/runner/work/_actions/kishikawakatsumi/xcresulttool/v1/webpack:/xcresulttool/node_modules/@actions/exec/lib/toolrunner.js:23:1)
    at /Users/runner/work/_actions/kishikawakatsumi/xcresulttool/v1/webpack:/xcresulttool/node_modules/@actions/exec/lib/toolrunner.js:395:1
    at new Promise (<anonymous>)
    at ToolRunner.<anonymous> (/Users/runner/work/_actions/kishikawakatsumi/xcresulttool/v1/webpack:/xcresulttool/node_modules/@actions/exec/lib/toolrunner.js:395:1)
```

**Comment by mackoj** [comment]
I did share with you @kishikawakatsumi on twitter in a private message a file that demo this issue.

**Comment by den2207** [comment]
@kishikawakatsumi Hi! I'm encountering a similar issue, getting Error: spawn E2BIG when running tests with xcresulttool. Is there a known workaround or fix for this issue? I would really appreciate any advice.
